name: Deploy to server

on:
  push:
    branches: [develop]

jobs:
  second_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Working dir
        run: ls -al
      - name: Action
        uses: actions/checkout@v4
      - name: Working dir after action
        run: ls -al

  third_job:
    if: ${{ github.ref == 'refs/heads/develop'}}
    needs: second_job
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo 2"
