name: "Deploy 0buHtiG0"

on:
  push:
    branches: ["develop"]

jobs:
  deploy-0buHtiG0:
    runs-on: ubuntu-latest
    steps:
	  - run: echo "Hacemos pull del código"
	  - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"
	  - run: echo "Todo listo!"    
