name: Deploy to server

on:
  push:
    branches: [develop]

jobs:
  second_jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  third_jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Hola Mundo 2
        run: echo "Hola Mundo 2"
